### ISSUE TITLE
教程变量名字打错了

### ISSUE THREAD

**Issue by longgyy** [hansyao/auto_api_call#1]
在本项目settings->Actions secrets新建New secrets命名为GH_SECRET，将上面申请到的Personal access token粘贴进去。

根据workflows中的yml文件，该变量应该是命名为GH_TOKEN

**Comment by hansyao** [comment]
changes committed. thanks!

**Comment by hansyao** [comment]
我看你fork的actions，api调用全部失败了嘛，估计是refresh_token你填错了

God_Long ***@***.***>于2021年8月31日 周二下午8:11写道：
